version: '3.8'

services:
  frontend:
    build: ./app
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BW_CLIENTID=${BW_CLIENTID:-}
      - BW_CLIENTSECRET=${BW_CLIENTSECRET:-}
    command: ["npm", "run", "dev:mock", "--", "--host"]
